name: dockerfile
"on":
  push:
    paths:
    - .github/workflows/dockerfile.yml
    - build/dockerfile/Dockerfile.dockerfile
    - build/dockerfile/Dockerfile.version
    - build/dockerfile/Makefile
  schedule:
  - cron: 0 1 * * *
jobs:
  dockerfile:
    runs-on:
    - ubuntu-latest
    defaults:
      run:
        working-directory: build/dockerfile
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      name: Login ghcr.io
      with:
        password: ${{ secrets.CR_PAT }}
        registry: ghcr.io
        username: ${{ github.repository_owner }}
    - uses: docker/login-action@v1
      name: Login docker.io
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
    - id: prepare
      name: prepare
      env:
        NAME: dockerfile
      run: |-
        if [[ ${{ github.ref }} != "refs/heads/master" ]]; then
          export TAG=temp-${{ github.sha }}
        fi
        make prepare
    - uses: docker/build-push-action@v2
      name: Push
      with:
        build-args: ${{ steps.prepare.outputs.build_args }}
        context: build/dockerfile
        file: build/dockerfile/Dockerfile.dockerfile
        labels: |-
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: |-
          ghcr.io/querycap/ci-infra/${{ steps.prepare.outputs.image }}
          docker.io/querycap/${{ steps.prepare.outputs.image }}
