name: dockerfile
"on":
  push:
    paths:
    - build/dockerfile/Dockerfile.dockerfile
    - build/dockerfile/Dockerfile.version
jobs:
  dockerfile:
    runs-on:
    - ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USERNAME }}
    - name: Versioned Build
      if: github.ref == 'refs/heads/master'
      run: cd build/dockerfile && make build HUB=querycap NAME=dockerfile
    - name: Temp Build
      if: github.ref != 'refs/heads/master'
      run: cd build/dockerfile && make build HUB=querycap NAME=dockerfile TAG=temp-${{ github.sha }}
